### ISSUE TITLE
Q: Wait - we already have a requirements document - shall I copy it over to arc42?

### ISSUE THREAD

**Issue by rdmueller** [arc42/faq.arc42.org-site#1]
A: No, but it would make sense to reference it and distill the architecture requirements from it.
Those architecture requirements should be part of your arc42 documentation.
Some of the overall requirements are unimportant for the architecture, like the color scheme of the application. Others contain hidden architectural decisions. So it is your task to distill these architectonically important requirements and only reference the overall requirements.

**Comment by gernotstarke** [comment]
imho we forget about this for now. wont'fix.
