### ISSUE TITLE
Check footer-style

### ISSUE THREAD

**Issue by Per-Starke** [arc42/faq.arc42.org-site#47]
@gernotstarke Please check if the footer with the "supported by INNOQ"-SVG is okay like this.

Shall I put it on other pages as well like this? On which pages?

Or do you want any changes?

**Comment by gernotstarke** [comment]
In principle, very nice. Please remove the bold in your name, and rephrase the last line to:

Maintained by Gernot Starke, supported by Peter Hruschka and Per Starke Web Development.

Then use this layout also for docs.arc42.org.

For quality  it's just me and you.

Please propose solutions for canvas, arc42.de and arc42.org visually first, without changing the production sites...

**Comment by Per-Starke** [comment]
Allrighty :)

- [ ] FAQ
- [ ] Docs
- [ ] Quality
- [ ] proposal for others

**Comment by Per-Starke** [comment]
@gernotstarke Please have a look at [this proposal for the footer for the arc42.de-site](https://arc42-footer-tester.github.io/). It's responsive as well of course.

**Comment by gernotstarke** [comment]
awesome, genau so...
